-- Create locations table
CREATE TABLE IF NOT EXISTS public.locations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    state TEXT NOT NULL,
    city TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    UNIQUE(state, city)
);

-- RLS
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "locations_select_policy"
    ON public.locations FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "locations_insert_policy"
    ON public.locations FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "locations_update_policy"
    ON public.locations FOR UPDATE
    USING (auth.role() = 'authenticated');

CREATE POLICY "locations_delete_policy"
    ON public.locations FOR DELETE
    USING (auth.role() = 'authenticated');

-- Insert initial data
INSERT INTO public.locations (state, city) VALUES
('Amazonas', 'Alto Orinoco'),
('Amazonas', 'Atabapo'),
('Amazonas', 'Atures'),
('Amazonas', 'Autana'),
('Amazonas', 'Manapiare'),
('Amazonas', 'Maroa'),
('Amazonas', 'Río Negro'),
('Anzoátegui', 'Anaco'),
('Anzoátegui', 'Aragua'),
('Anzoátegui', 'Barcelona'),
('Anzoátegui', 'Diego Bautista Urbaneja'),
('Anzoátegui', 'Fernando de Peñalver'),
('Anzoátegui', 'Francisco del Carmen Carvajal'),
('Anzoátegui', 'Francisco de Miranda'),
('Anzoátegui', 'Guanta'),
('Anzoátegui', 'Independencia'),
('Anzoátegui', 'José Gregorio Monagas'),
('Anzoátegui', 'Juan Antonio Sotillo'),
('Anzoátegui', 'Juan Manuel Cajigal'),
('Anzoátegui', 'Libertad'),
('Anzoátegui', 'Manuel Ezequiel Bruzual'),
('Anzoátegui', 'Pedro María Freites'),
('Anzoátegui', 'Píritu'),
('Anzoátegui', 'Puerto La Cruz'),
('Anzoátegui', 'San José de Guanipa'),
('Anzoátegui', 'San Juan de Capistrano'),
('Anzoátegui', 'Santa Ana'),
('Anzoátegui', 'Simón Bolívar'),
('Anzoátegui', 'Simón Rodríguez'),
('Anzoátegui', 'Sir Arthur McGregor'),
('Apure', 'Achaguas'),
('Apure', 'Biruaca'),
('Apure', 'Muñoz'),
('Apure', 'Páez'),
('Apure', 'Pedro Camejo'),
('Apure', 'Rómulo Gallegos'),
('Apure', 'San Fernando'),
('Aragua', 'Bolívar'),
('Aragua', 'Camatagua'),
('Aragua', 'Francisco Linares Alcántara'),
('Aragua', 'Girardot'),
('Aragua', 'José Ángel Lamas'),
('Aragua', 'José Félix Ribas'),
('Aragua', 'José Rafael Revenga'),
('Aragua', 'Libertador'),
('Aragua', 'Maracay'),
('Aragua', 'Mario Briceño Iragorry'),
('Aragua', 'Ocumare de la Costa de Oro'),
('Aragua', 'San Casimiro'),
('Aragua', 'San Sebastián'),
('Aragua', 'Santiago Mariño'),
('Aragua', 'Santos Michelena'),
('Aragua', 'Sucre'),
('Aragua', 'Tovar'),
('Aragua', 'Urdaneta'),
('Aragua', 'Zamora'),
('Barinas', 'Alberto Arvelo Torrealba'),
('Barinas', 'Andrés Eloy Blanco'),
('Barinas', 'Antonio José de Sucre'),
('Barinas', 'Arismendi'),
('Barinas', 'Barinas'),
('Barinas', 'Bolívar'),
('Barinas', 'Cruz Paredes'),
('Barinas', 'Ezequiel Zamora'),
('Barinas', 'Obispos'),
('Barinas', 'Pedraza'),
('Barinas', 'Rojas'),
('Barinas', 'Sosa'),
('Bolívar', 'Angostura'),
('Bolívar', 'Caroní'),
('Bolívar', 'Cedeño'),
('Bolívar', 'Ciudad Bolívar'),
('Bolívar', 'El Callao'),
('Bolívar', 'Gran Sabana'),
('Bolívar', 'Heres'),
('Bolívar', 'Padre Pedro Chien'),
('Bolívar', 'Piar'),
('Bolívar', 'Puerto Ordaz'),
('Bolívar', 'Roscio'),
('Bolívar', 'San Félix'),
('Bolívar', 'Sifontes'),
('Bolívar', 'Sucre'),
('Carabobo', 'Bejuma'),
('Carabobo', 'Carlos Arvelo'),
('Carabobo', 'Diego Ibarra'),
('Carabobo', 'Guacara'),
('Carabobo', 'Juan José Mora'),
('Carabobo', 'Libertador'),
('Carabobo', 'Los Guayos'),
('Carabobo', 'Miranda'),
('Carabobo', 'Montalbán'),
('Carabobo', 'Naguanagua'),
('Carabobo', 'Puerto Cabello'),
('Carabobo', 'San Diego'),
('Carabobo', 'San Joaquín'),
('Carabobo', 'Valencia'),
('Cojedes', 'Anzoátegui'),
('Cojedes', 'Ezequiel Zamora'),
('Cojedes', 'Girardot'),
('Cojedes', 'Lima Blanco'),
('Cojedes', 'Pao de San Juan Bautista'),
('Cojedes', 'Ricaurte'),
('Cojedes', 'Rómulo Gallegos'),
('Cojedes', 'Tinaco'),
('Cojedes', 'Tinaquillo'),
('Delta Amacuro', 'Antonio Díaz'),
('Delta Amacuro', 'Casacoima'),
('Delta Amacuro', 'Pedernales'),
('Delta Amacuro', 'Tucupita'),
('Dependencias Federales', 'Archipiélago Los Roques'),
('Dependencias Federales', 'Dependencias Federales (Otras)'),
('Distrito Capital', 'Libertador'),
('Distrito Capital', 'Caracas'),
('Falcón', 'Acosta'),
('Falcón', 'Bolívar'),
('Falcón', 'Buchivacoa'),
('Falcón', 'Cacique Manaure'),
('Falcón', 'Carirubana'),
('Falcón', 'Colina'),
('Falcón', 'Coro'),
('Falcón', 'Dabajuro'),
('Falcón', 'Democracia'),
('Falcón', 'Falcón'),
('Falcón', 'Federación'),
('Falcón', 'Jacura'),
('Falcón', 'Los Taques'),
('Falcón', 'Mauroa'),
('Falcón', 'Miranda'),
('Falcón', 'Monseñor Iturriza'),
('Falcón', 'Palmasola'),
('Falcón', 'Petit'),
('Falcón', 'Píritu'),
('Falcón', 'Punto Fijo'),
('Falcón', 'San Francisco'),
('Falcón', 'Silva'),
('Falcón', 'Sucre'),
('Falcón', 'Tocópero'),
('Falcón', 'Unión'),
('Falcón', 'Urumaco'),
('Falcón', 'Zamora'),
('Guárico', 'Camaguán'),
('Guárico', 'Chaguaramas'),
('Guárico', 'El Socorro'),
('Guárico', 'Francisco de Miranda'),
('Guárico', 'José Félix Ribas'),
('Guárico', 'José Tadeo Monagas'),
('Guárico', 'Juan Germán Roscio'),
('Guárico', 'Julián Mellado'),
('Guárico', 'Las Mercedes'),
('Guárico', 'Leonardo Infante'),
('Guárico', 'Ortiz'),
('Guárico', 'San Gerónimo de Guayabal'),
('Guárico', 'San José de Guaribe'),
('Guárico', 'Santa María de Ipire'),
('Guárico', 'Zaraza'),
('La Guaira', 'Vargas'),
('Lara', 'Andrés Eloy Blanco'),
('Lara', 'Barquisimeto'),
('Lara', 'Crespo'),
('Lara', 'Iribarren'),
('Lara', 'Jiménez'),
('Lara', 'Morán'),
('Lara', 'Palavecino'),
('Lara', 'Simón Planas'),
('Lara', 'Torres'),
('Lara', 'Urdaneta'),
('Mérida', 'Alberto Adriani'),
('Mérida', 'Andrés Bello'),
('Mérida', 'Antonio Pinto Salinas'),
('Mérida', 'Aricagua'),
('Mérida', 'Arzobispo Chacón'),
('Mérida', 'Campo Elías'),
('Mérida', 'Caracciolo Parra Olmedo'),
('Mérida', 'Cardenal Quintero'),
('Mérida', 'Guaraque'),
('Mérida', 'Julio César Salas'),
('Mérida', 'Justo Briceño'),
('Mérida', 'Libertador'),
('Mérida', 'Miranda'),
('Mérida', 'Obispo Ramos de Lora'),
('Mérida', 'Padre Noguera'),
('Mérida', 'Pueblo Llano'),
('Mérida', 'Rangel'),
('Mérida', 'Rivas Dávila'),
('Mérida', 'Santos Marquina'),
('Mérida', 'Sucre'),
('Mérida', 'Tovar'),
('Mérida', 'Tulio Febres Cordero'),
('Mérida', 'Zea'),
('Miranda', 'Acevedo'),
('Miranda', 'Andrés Bello'),
('Miranda', 'Baruta'),
('Miranda', 'Brión'),
('Miranda', 'Buroz'),
('Miranda', 'Carrizal'),
('Miranda', 'Chacao'),
('Miranda', 'Cristóbal Rojas'),
('Miranda', 'El Hatillo'),
('Miranda', 'Guaicaipuro'),
('Miranda', 'Independencia'),
('Miranda', 'Lander'),
('Miranda', 'Los Salias'),
('Miranda', 'Los Teques'),
('Miranda', 'Páez'),
('Miranda', 'Paz Castillo'),
('Miranda', 'Pedro Gual'),
('Miranda', 'Plaza'),
('Miranda', 'Simón Bolívar'),
('Miranda', 'Sucre'),
('Miranda', 'Urdaneta'),
('Miranda', 'Zamora'),
('Monagas', 'Acosta'),
('Monagas', 'Aguasay'),
('Monagas', 'Bolívar'),
('Monagas', 'Caripe'),
('Monagas', 'Cedeño'),
('Monagas', 'Ezequiel Zamora'),
('Monagas', 'Libertador'),
('Monagas', 'Maturín'),
('Monagas', 'Piar'),
('Monagas', 'Punceres'),
('Monagas', 'Santa Bárbara'),
('Monagas', 'Sotillo'),
('Monagas', 'Uracoa'),
('Nueva Esparta', 'Antolín del Campo'),
('Nueva Esparta', 'Arismendi'),
('Nueva Esparta', 'Díaz'),
('Nueva Esparta', 'García'),
('Nueva Esparta', 'Gómez'),
('Nueva Esparta', 'Maneiro'),
('Nueva Esparta', 'Marcano'),
('Nueva Esparta', 'Mariño'),
('Nueva Esparta', 'Península de Macanao'),
('Nueva Esparta', 'Tubores'),
('Nueva Esparta', 'Villalba'),
('Portuguesa', 'Agua Blanca'),
('Portuguesa', 'Araure'),
('Portuguesa', 'Esteller'),
('Portuguesa', 'Guanare'),
('Portuguesa', 'Guanarito'),
('Portuguesa', 'Monseñor José Vicente de Unda'),
('Portuguesa', 'Ospino'),
('Portuguesa', 'Páez'),
('Portuguesa', 'Papelón'),
('Portuguesa', 'San Genaro de Boconoíto'),
('Portuguesa', 'San Rafael de Onoto'),
('Portuguesa', 'Santa Rosalía'),
('Portuguesa', 'Sucre'),
('Portuguesa', 'Turén'),
('Sucre', 'Andrés Eloy Blanco'),
('Sucre', 'Andrés Mata'),
('Sucre', 'Arismendi'),
('Sucre', 'Benítez'),
('Sucre', 'Bermúdez'),
('Sucre', 'Bolívar'),
('Sucre', 'Cajigal'),
('Sucre', 'Cruz Salmerón Acosta'),
('Sucre', 'Libertador'),
('Sucre', 'Mariño'),
('Sucre', 'Mejía'),
('Sucre', 'Montes'),
('Sucre', 'Ribero'),
('Sucre', 'Sucre'),
('Sucre', 'Valdez'),
('Táchira', 'Andrés Bello'),
('Táchira', 'Antonio Rómulo Costa'),
('Táchira', 'Ayacucho'),
('Táchira', 'Bolívar'),
('Táchira', 'Cárdenas'),
('Táchira', 'Córdoba'),
('Táchira', 'Fernández Feo'),
('Táchira', 'Francisco de Miranda'),
('Táchira', 'García de Hevia'),
('Táchira', 'Guásimos'),
('Táchira', 'Independencia'),
('Táchira', 'Jáuregui'),
('Táchira', 'José María Vargas'),
('Táchira', 'Junín'),
('Táchira', 'Libertad'),
('Táchira', 'Libertador'),
('Táchira', 'Lobatera'),
('Táchira', 'Michelena'),
('Táchira', 'Panamericano'),
('Táchira', 'Pedro María Ureña'),
('Táchira', 'Rafael Urdaneta'),
('Táchira', 'Samuel Darío Maldonado'),
('Táchira', 'San Cristóbal'),
('Táchira', 'San Judas Tadeo'),
('Táchira', 'Seboruco'),
('Táchira', 'Simón Rodríguez'),
('Táchira', 'Sucre'),
('Táchira', 'Torbes'),
('Táchira', 'Uribante'),
('Trujillo', 'Andrés Bello'),
('Trujillo', 'Boconó'),
('Trujillo', 'Bolívar'),
('Trujillo', 'Candelaria'),
('Trujillo', 'Carache'),
('Trujillo', 'Escuque'),
('Trujillo', 'José Felipe Márquez Cañizalez'),
('Trujillo', 'Juan Vicente Campos Elías'),
('Trujillo', 'La Ceiba'),
('Trujillo', 'Miranda'),
('Trujillo', 'Monte Carmelo'),
('Trujillo', 'Motatán'),
('Trujillo', 'Pampán'),
('Trujillo', 'Pampanito'),
('Trujillo', 'Rafael Rangel'),
('Trujillo', 'San Rafael de Carvajal'),
('Trujillo', 'Sucre'),
('Trujillo', 'Trujillo'),
('Trujillo', 'Urdaneta'),
('Trujillo', 'Valera'),
('Yaracuy', 'Arístides Bastidas'),
('Yaracuy', 'Bolívar'),
('Yaracuy', 'Bruzual'),
('Yaracuy', 'Cocorote'),
('Yaracuy', 'Independencia'),
('Yaracuy', 'José Antonio Páez'),
('Yaracuy', 'La Trinidad'),
('Yaracuy', 'Manuel Monge'),
('Yaracuy', 'Nirgua'),
('Yaracuy', 'Peña'),
('Yaracuy', 'San Felipe'),
('Yaracuy', 'Sucre'),
('Yaracuy', 'Urachiche'),
('Yaracuy', 'Veroes'),
('Zulia', 'Almirante Padilla'),
('Zulia', 'Baralt'),
('Zulia', 'Cabimas'),
('Zulia', 'Catatumbo'),
('Zulia', 'Colón'),
('Zulia', 'Francisco Javier Pulgar'),
('Zulia', 'Jesús Enrique Lossada'),
('Zulia', 'Jesús María Semprún'),
('Zulia', 'La Cañada de Urdaneta'),
('Zulia', 'Lagunillas'),
('Zulia', 'Machiques de Perijá'),
('Zulia', 'Mara'),
('Zulia', 'Maracaibo'),
('Zulia', 'Miranda'),
('Zulia', 'Páez'),
('Zulia', 'Rosario de Perijá'),
('Zulia', 'San Francisco'),
('Zulia', 'Santa Rita'),
('Zulia', 'Simón Bolívar'),
('Zulia', 'Sucre'),
('Zulia', 'Valmore Rodríguez') ON CONFLICT DO NOTHING;
